"""End-to-end confirmation of the RHEA per-execution teardown via the CONTAINER backend.

Provisions rhea-server as a Docker CONTAINER (host-conda-independent — the only path that runs
tools on a host with a broken/missing conda), DOGFOODING the orchestrator's own production spec:
the docker-run command is generated by ``_make_rhea_container_spec`` + ``container_run_args`` (the
exact code apecx-mcp runs when ``APECX_RHEA_BACKEND=container``), so this test also guards that the
generated command is real. The ``live_rhea`` fixture (1) self-heals the DB schema via rhea's
self-migrating ``update_tools``, (2) reuses an already-healthy ``:3001`` or spawns the container
from the orchestrator spec, (3) waits for ``:3001`` healthy, and (4) SKIPS cleanly (never
flaky-FAILS) when Docker / the infra / the pre-built image is absent. Given a healthy rhea it
CONFIRMS the teardown: two real MUSCLE runs leave no net-new persisted ProxyStore Redis keys (the
per-call eviction holds), deciding on output VALUES not the run's status field (G127).

Requires the rhea-server image (auto-built by the orchestrator, or ``docker build``); skips with that hint when
absent. The first MUSCLE call cold-builds the per-tool conda env INSIDE the container (~15-20s for
MUSCLE); ``rhea_muscle_alignment``'s ``execution_timeout`` covers it.
"""

from __future__ import annotations

import asyncio
import os
import subprocess
import time
import urllib.request
from pathlib import Path

import pytest

pytestmark = pytest.mark.integration

_RHEA_REPO = Path(__file__).resolve().parents[3] / "rhea"
_RHEA_PY = _RHEA_REPO / ".venv" / "bin" / "python"
_MCP_URL = "http://localhost:3001/mcp/"
_FASTA = ">a\nMKTAYIAKQR\n>b\nMKTAYIAKQR\n>c\nMKTAYIAKQK\n"

# Standard apecx-setup-infra layout (containers: apecx-rhea-postgres:5435, apecx-redis:6379,
# apecx-rhea-minio:9000). A test may know the provisioned layout; if it drifts, update here.
_RHEA_ENV = {
    "HOST": "localhost",
    "PORT": "3001",
    "DATABASE_URL": "postgresql+asyncpg://postgres:postgres@localhost:5435/rhea",
    "REDIS_HOST": "localhost",
    "REDIS_PORT": "6379",
    "AGENT_REDIS_HOST": "localhost",
    "AGENT_REDIS_PORT": "6379",
    "MINIO_ENDPOINT": "localhost:9000",
    "MINIO_ACCESS_KEY": "minioadmin",
    "MINIO_SECRET_KEY": "minioadmin",
    "EMBEDDING_URL": "http://localhost:11434/v1",
    "EMBEDDING_KEY": "EMPTY",
    "MODEL": "mxbai-embed-large",
    "PARSL_CONTAINER_BACKEND": "local",
    "RHEA_CONDA_ENVS_DIR": "/tmp/apecx-rhea/conda/envs",
}


def _http_code(url: str, timeout: float = 4.0) -> int:
    try:
        urllib.request.urlopen(url, timeout=timeout)  # noqa: S310
        return 200
    except urllib.error.HTTPError as e:  # type: ignore[attr-defined]
        return e.code  # 406 = MCP server UP
    except Exception:
        return 0


def _healthy(url: str = _MCP_URL) -> bool:
    code = _http_code(url)
    return code not in (0, 500)  # 4xx (406) = up; 500 = backend down; 0 = not listening


def _redis_reachable() -> bool:
    try:
        import socket

        with socket.create_connection(("localhost", 6379), timeout=2):
            return True
    except Exception:
        return False


def _self_heal_schema_and_ingest() -> bool:
    """Run rhea's self-migrating update_tools (idempotent) so galaxytools exists + muscle is
    ingested, regardless of a churned/fresh postgres. Returns True on success."""
    if not _RHEA_PY.exists():
        return False
    env = {**os.environ, **_RHEA_ENV, "RHEA_INGEST_ONLY": "muscle", "RHEA_INGEST_LIMIT": "25"}
    try:
        r = subprocess.run(
            [str(_RHEA_PY), "-m", "rhea.preprocess.update_tools"],
            cwd=str(_RHEA_REPO),
            env=env,
            capture_output=True,
            text=True,
            timeout=300,
        )
        return r.returncode == 0
    except Exception:
        return False


_IMAGE = os.environ.get("APECX_RHEA_IMAGE", "apecx-rhea-server:local")
_TEST_CONTAINER = "apecx-rhea-teardown-e2e"


def _docker() -> str | None:
    import shutil

    return shutil.which("docker")


def _ensure_rhea_importable() -> bool:
    """rhea_muscle_alignment's prereq gate needs `rhea` importable in THIS test
    process regardless of how pytest was invoked (PYTHONPATH)."""
    import importlib.util
    import sys

    if str(_RHEA_REPO) not in sys.path:
        sys.path.insert(0, str(_RHEA_REPO))
    os.environ["RHEA_MCP_URL"] = _MCP_URL
    return (
        importlib.util.find_spec("rhea") is not None
        and importlib.util.find_spec("rhea.utils.proxy") is not None
    )


def _container_argv(docker: str) -> list[str]:
    """The EXACT production docker-run for the rhea CONTAINER backend, generated
    by the orchestrator's own spec (dogfood), with a test-specific name so it
    can't clobber an operator/orchestrator-owned ``apecx-rhea-server``."""
    import dataclasses

    os.environ["APECX_RHEA_BACKEND"] = "container"
    os.environ["APECX_RHEA_IMAGE"] = _IMAGE
    from apecx_integration.infrastructure.containers import container_run_args
    from apecx_integration.infrastructure.orchestrator import _default_backend_specs

    spec = {s.name: s for s in _default_backend_specs()}["rhea_mcp"].container
    spec = dataclasses.replace(spec, container_name=_TEST_CONTAINER)
    return [docker, *container_run_args(spec)]


@pytest.fixture(scope="module")
def live_rhea():
    docker = _docker()
    if docker is None or not _redis_reachable():
        pytest.skip("needs Docker + the apecx infra stack (redis)")
    if not _ensure_rhea_importable():
        pytest.skip("`rhea` (+ rhea.utils.proxy deps) not importable in the test venv")
    # Schema must hold regardless of provisioning (idempotent self-heal).
    if not _self_heal_schema_and_ingest():
        pytest.skip("could not self-heal the rhea schema (infra not provisioned)")
    # Reuse an already-running healthy server (operator / CI / orchestrator-provided).
    if _healthy():
        yield _MCP_URL
        return
    # Otherwise provision the CONTAINER backend. Requires the pre-built image.
    if subprocess.run([docker, "image", "inspect", _IMAGE], capture_output=True).returncode != 0:
        pytest.skip(
            f"rhea-server image {_IMAGE!r} not built; the orchestrator auto-builds it on "
            f"apecx-mcp startup, or build it manually: "
            f"`docker build -t {_IMAGE} -f {_RHEA_REPO}/Dockerfile {_RHEA_REPO}`"
        )
    subprocess.run([docker, "rm", "-f", _TEST_CONTAINER], capture_output=True)
    spawn = subprocess.run(_container_argv(docker), capture_output=True, text=True)
    if spawn.returncode != 0:
        pytest.skip(f"docker run of {_IMAGE} failed: {spawn.stderr.strip()[:300]}")
    try:
        deadline = time.monotonic() + 180
        while time.monotonic() < deadline:
            if _healthy():
                break
            if (
                subprocess.run(
                    [docker, "ps", "-q", "-f", f"name=^{_TEST_CONTAINER}$"],
                    capture_output=True,
                    text=True,
                ).stdout.strip()
                == ""
            ):
                logs = subprocess.run(
                    [docker, "logs", "--tail", "20", _TEST_CONTAINER],
                    capture_output=True,
                    text=True,
                )
                pytest.skip(f"rhea container exited during startup: {logs.stderr.strip()[:300]}")
            time.sleep(5)
        else:
            pytest.skip("rhea container did not become healthy within 180s")
        yield _MCP_URL
    finally:
        subprocess.run([docker, "rm", "-f", _TEST_CONTAINER], capture_output=True)


def _keyset():
    from redis import Redis

    # Decode to str so prefix checks (file:/agent:) work; set-diffs are unaffected.
    return {k.decode(errors="replace") for k in Redis(host="localhost", port=6379).keys("*")}


def _run_muscle(url: str) -> dict:
    os.environ["RHEA_MCP_URL"] = url
    from apecx_integration.mcp_surface.tools.eo_primitives import run_workflow
    from apecx_integration.mcp_surface.workflow_registry import _clear_workflow_cache

    _clear_workflow_cache()
    return asyncio.run(run_workflow("rhea_muscle_alignment", {"fasta_text": _FASTA}))


def test_rhea_teardown_no_per_run_key_growth(live_rhea):
    """Two REAL MUSCLE runs on a live rhea confirm the rhea ProxyStore per-execution teardown:
    a 2nd run leaves ZERO net-new ``file:`` byte keys and ZERO net-new academy agent keys (the
    RheaFileToolStep eviction of BOTH the ProxyStore object key AND the file-byte key holds, and
    the tool agent is server-lifetime/reused). Academy mailbox residual (``active:``/``queue:``)
    is a separate framework concern — surfaced, not asserted (see below).

    Failure semantics (the flakiness accommodation): status is now HONEST (G127 driver fix), so a
    MUSCLE failure surfaces as status=error rather than a masked ok. But a rhea-SERVER-side
    execution failure (Parsl worker never returns a handle, conda env not provisioned, embedding
    backend down) is a rhea-infra problem, NOT a teardown regression — so we SKIP on it. This test
    FAILS only on the rhea-owned per-run key growth (the eviction leak it exists to catch); it
    can therefore only CONFIRM the teardown when rhea's MUSCLE leg genuinely completes."""
    # run 1 primes the per-tool conda env + agent (cold); we measure the DELTA the 2nd run
    # adds (after2 - after1), so only the post-run-1 keyset matters as the baseline.
    r1 = _run_muscle(live_rhea)
    if r1.get("status") != "ok":
        pytest.skip(
            "rhea MUSCLE leg did not complete (rhea-server-side execution unavailable — Parsl "
            f"worker / conda env / embedding backend); not a teardown regression: {r1.get('error')}"
        )
    after1 = _keyset()
    r2 = _run_muscle(live_rhea)
    if r2.get("status") != "ok":
        pytest.skip(
            f"rhea MUSCLE 2nd run did not complete (rhea-infra, not teardown): {r2.get('error')}"
        )
    after2 = _keyset()

    new_run2 = after2 - after1

    # PRIMARY assertion — the rhea ProxyStore teardown this test exists to confirm.
    # RheaFileToolStep stages TWO Redis keys per file: the ProxyStore object key AND the
    # file-byte key (``file:<uuid>``, RheaFileHandle). The per-execution eviction must clear
    # BOTH on every call, so a 2nd run leaves ZERO net-new ``file:`` byte keys. (The original
    # teardown evicted only the object key — the file-byte payload leaked every call; this
    # guards that regression.)
    file_leak = {k for k in new_run2 if k.startswith("file:")}
    assert not file_leak, (
        f"rhea ProxyStore file-byte keys leaked in run 2 (eviction broken): {sorted(file_leak)}"
    )

    # The rhea tool AGENT is server-lifetime (cached + reused across calls for the same tool),
    # so its academy agent / agent_handle keys must NOT grow run-over-run.
    agent_leak = {k for k in new_run2 if k.startswith("agent")}
    assert not agent_leak, f"rhea academy agent keys grew run-over-run: {sorted(agent_leak)}"

    # SEPARATE framework residual — surfaced for visibility, NOT asserted. Academy's Redis
    # exchange marks a terminated mailbox INACTIVE but never DELETES its ``active:<uid>`` /
    # ``queue:<uid>`` keys (academy/exchange/redis.py), and the rhea server registers a
    # per-connection user client — so a small, NON-DETERMINISTIC number of academy keys
    # (typically 1-2) lingers per run. That is an academy-library + rhea-server lifecycle
    # concern, NOT the rhea ProxyStore teardown this test owns; asserting a tight bound here
    # flakes on academy's exchange lifecycle. We print it (no silent cap) so a reviewer sees
    # the residual; a gross academy leak is tracked + fixed separately, not masked here.
    academy_residual = sorted(new_run2 - file_leak - agent_leak)
    print(
        f"[teardown-e2e] academy framework residual in run 2 (NOT asserted, separate concern): "
        f"{len(academy_residual)} keys {academy_residual}"
    )
