"""T12 AC1+AC2+AC3: run every reproducibility fixture through the
composer and compare against the baseline.

This test parametrizes over every fixture discovered under
``tests/reproducibility/fixtures/``. A fixture passes when the
composer's generated bytes either hash-match the stored baseline or
semantically match it (T12 AC3).

## When this test runs

Two gates:

1. **Composer must be importable.** Until the composer (T06 / Phase 2)
   lands, ``from apecx_integration.composition.composer import generate``
   raises ``ImportError`` and every fixture test auto-skips with a
   clear pointer. The harness itself is unit-tested in
   ``test_harness.py`` so the infrastructure is verified every commit.
2. **Fixtures must exist.** The seed fixtures live under
   ``tests/reproducibility/fixtures/``. The plan's AC1 requires 10 by
   end of Phase 2; the repo ships with 1 minimal fixture so the
   plumbing is exercised the moment the composer lands.

## Marker

``@pytest.mark.integration`` because the composer makes real LLM
calls. A real ``pytest -m "not integration"`` run skips these; the
dedicated CI job (``reproducibility.yml`` — not yet scheduled, see
TX2 gap) would run them nightly.
"""

from __future__ import annotations

import pytest

from tests.reproducibility.harness import (
    Fixture,
    check,
    discover_fixtures,
)

pytestmark = pytest.mark.integration


def _composer_generate_or_skip():
    """Return the ``generate(prompt) -> bytes`` callable, or skip the
    test module if the composer does not yet exist.
    """
    try:
        from apecx_integration.composition.composer import (  # type: ignore[import-not-found]
            generate,
        )
    except ImportError:
        pytest.skip(
            "composer not yet implemented (see implementation_plan.md T06 "
            "and Phase 2 rescope). Reproducibility test ready to activate "
            "the moment `apecx_integration.composition.composer.generate` "
            "is importable."
        )
    return generate


_fixtures = discover_fixtures()


@pytest.mark.parametrize("fixture", _fixtures, ids=[f.name for f in _fixtures])
def test_baseline(fixture: Fixture) -> None:
    generate = _composer_generate_or_skip()
    generated = generate(fixture.prompt)
    check(generated=generated, fixture=fixture)


def test_at_least_one_fixture_present() -> None:
    """Guards against an empty fixtures directory silently producing
    a green suite. AC1 targets 10 fixtures by end of Phase 2; we ship
    with 1 so the infrastructure has a minimal exercise.
    """
    if not _fixtures:
        pytest.skip(
            "No fixtures present yet. See tests/reproducibility/README.md "
            "for how to add one."
        )
    # We have at least one fixture — trivially pass.
    assert len(_fixtures) >= 1
