"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-04-21 15:23:35.538193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import apecx_integration.control_plane.models.base  # noqa: F401 — UUIDString referenced by autogen


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('io_schema', sa.JSON(), nullable=False),
    sa.Column('implementation_path', sa.Text(), nullable=False),
    sa.Column('test_status', sa.Enum('PASSING', 'FAILING', 'UNTESTED', name='componentteststatus', native_enum=False, length=48), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run',
    sa.Column('id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('workflow_config_id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='runstatus', native_enum=False, length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_run_id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['parent_run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocation_estimate',
    sa.Column('id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=False),
    sa.Column('run_id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=False),
    sa.Column('estimated_core_hours', sa.Float(), nullable=False),
    sa.Column('estimated_wall_time_seconds', sa.Float(), nullable=False),
    sa.Column('estimated_memory_gb', sa.Float(), nullable=True),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('user_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_core_hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allocation_estimate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocation_estimate_run_id'), ['run_id'], unique=False)

    op.create_table('provenance_event',
    sa.Column('id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=False),
    sa.Column('run_id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('RUN_STARTED', 'STEP_STARTED', 'STEP_COMPLETED', 'APPROVAL_REQUESTED', 'APPROVAL_DECIDED', 'ARTIFACT_CREATED', 'WORKFLOW_GENERATED', 'ALLOCATION_ESTIMATED', 'ALLOCATION_CONFIRMED', 'RUN_COMPLETED', 'RUN_FAILED', name='provenanceeventtype', native_enum=False, length=48), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('prev_event_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provenance_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provenance_event_event_hash'), ['event_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_provenance_event_run_id'), ['run_id'], unique=False)

    op.create_table('step',
    sa.Column('id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=False),
    sa.Column('run_id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('executor', sa.Enum('LOCAL', 'GLOBUS_COMPUTE', 'PBS_BUNDLE', name='executorkind', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED_FOR_APPROVAL', 'COMPLETED', 'FAILED', 'SKIPPED', name='stepstatus', native_enum=False, length=48), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_artifact_ids', sa.JSON(), nullable=False),
    sa.Column('output_artifact_ids', sa.JSON(), nullable=False),
    sa.Column('log_location', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_run_id'), ['run_id'], unique=False)

    op.create_table('verified_synonym',
    sa.Column('id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=False),
    sa.Column('source_vocabulary', sa.String(length=128), nullable=False),
    sa.Column('query_term', sa.String(length=512), nullable=False),
    sa.Column('target_vocabulary', sa.String(length=128), nullable=False),
    sa.Column('canonical_term', sa.String(length=512), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_run_id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_by', sa.String(length=255), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('superseded_by', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['source_run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['verified_synonym.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_vocabulary', 'query_term', 'target_vocabulary', 'scope', 'is_active', name='uq_verified_synonym_tuple')
    )
    with op.batch_alter_table('verified_synonym', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verified_synonym_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_verified_synonym_query_term'), ['query_term'], unique=False)
        batch_op.create_index(batch_op.f('ix_verified_synonym_source_vocabulary'), ['source_vocabulary'], unique=False)
        batch_op.create_index(batch_op.f('ix_verified_synonym_target_vocabulary'), ['target_vocabulary'], unique=False)

    op.create_table('approval',
    sa.Column('id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=False),
    sa.Column('step_id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=False),
    sa.Column('kind', sa.Enum('HARD', 'SOFT', 'SILENT', 'ALLOCATION', name='approvalkind', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'APPROVED_WITH_MODIFICATIONS', 'REJECTED', 'AUTO_APPROVED', 'TIMED_OUT', name='approvalstatus', native_enum=False, length=48), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_step_id'), ['step_id'], unique=False)

    op.create_table('artifact',
    sa.Column('id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=False),
    sa.Column('run_id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=False),
    sa.Column('step_id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=True),
    sa.Column('kind', sa.Enum('INPUT', 'INTERMEDIATE', 'OUTPUT', 'GENERATED_WORKFLOW', 'GENERATED_PYTHON', name='artifactkind', native_enum=False, length=48), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_run_id'), ['run_id'], unique=False)

    op.create_table('generated_artifact',
    sa.Column('artifact_id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=False),
    sa.Column('source_prompt', sa.Text(), nullable=False),
    sa.Column('library_version', sa.String(length=64), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=False),
    sa.Column('llm_model_version_hash', sa.String(length=64), nullable=False),
    sa.Column('composition_summary', sa.JSON(), nullable=False),
    sa.Column('parent_artifact_id', apecx_integration.control_plane.models.base.UUIDString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], ),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['artifact.id'], ),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    # Circular FK: run.workflow_config_id -> artifact.id. Deferred to post-create
    # so the topological order is resolvable on Postgres (SQLite tolerates forward
    # refs, Postgres does not). batch_alter_table handles both backends uniformly.
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_run_workflow_config', 'artifact', ['workflow_config_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_constraint('fk_run_workflow_config', type_='foreignkey')
    op.drop_table('generated_artifact')
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_run_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_content_hash'))

    op.drop_table('artifact')
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_step_id'))
        batch_op.drop_index(batch_op.f('ix_approval_status'))

    op.drop_table('approval')
    with op.batch_alter_table('verified_synonym', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verified_synonym_target_vocabulary'))
        batch_op.drop_index(batch_op.f('ix_verified_synonym_source_vocabulary'))
        batch_op.drop_index(batch_op.f('ix_verified_synonym_query_term'))
        batch_op.drop_index(batch_op.f('ix_verified_synonym_is_active'))

    op.drop_table('verified_synonym')
    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_run_id'))

    op.drop_table('step')
    with op.batch_alter_table('provenance_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provenance_event_run_id'))
        batch_op.drop_index(batch_op.f('ix_provenance_event_event_hash'))

    op.drop_table('provenance_event')
    with op.batch_alter_table('allocation_estimate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocation_estimate_run_id'))

    op.drop_table('allocation_estimate')
    op.drop_table('run')
    op.drop_table('component')
    # ### end Alembic commands ###
