#!/usr/bin/env python3
"""Generate the apecx_integration code index (docs/global_index.md + docs/detailed_index.md).

Why generated, not hand-written: a hand-maintained per-file/per-function index rots the first
time someone forgets to update it — silently. Generating from the code (AST + docstrings) turns
"update on every change" into a re-run, and the ``--check`` mode makes a stale index a hard
pre-commit failure instead of a silent drift.

- ``global_index.md`` — one row per source file: path -> module-docstring first line. Compact;
  meant to be read at session start.
- ``detailed_index.md`` — per file: its classes (with bases) and functions/methods (with a
  compact signature) + each one's docstring first line. Consult on demand (grep), not top-to-bottom.

Usage:
    python scripts/gen_index.py            # (re)write both files in place
    python scripts/gen_index.py --check    # exit 1 if either file is stale (pre-commit gate)

Deterministic: files sorted by path, members in source order; identical input -> identical output.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "src" / "apecx_integration"
GLOBAL_INDEX = REPO / "docs" / "global_index.md"
DETAILED_INDEX = REPO / "docs" / "detailed_index.md"

_GENERATED_NOTE = (
    "> Generated by `scripts/gen_index.py` — do NOT edit by hand. Re-run the script after code "
    "changes; a pre-commit gate (`code-index-fresh`) blocks a commit whose index is stale."
)


def _first_doc_line(doc: str | None) -> str:
    """First non-blank line of a docstring, or '' when absent."""
    if not doc:
        return ""
    for line in doc.strip().splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


def _iter_source_files() -> list[Path]:
    """Every non-cache .py under src/apecx_integration, sorted by path (deterministic)."""
    return sorted(p for p in SRC.rglob("*.py") if "__pycache__" not in p.parts)


def _rel(path: Path) -> str:
    """Repo-root-relative POSIX path for stable output across machines.

    Falls back to the plain path when it is not under the repo (only the ``--check``
    error message can hit that — every indexed source file is under SRC/REPO)."""
    try:
        return path.relative_to(REPO).as_posix()
    except ValueError:
        return path.as_posix()


def _package(path: Path) -> str:
    """Top-level package under apecx_integration ('(root)' for files directly in it)."""
    parts = path.relative_to(SRC).parts
    return parts[0] if len(parts) > 1 else "(root)"


def _signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """Compact ``(args)`` signature via ast.unparse; degrades to ``(...)`` on any oddity."""
    try:
        return f"({ast.unparse(node.args)})"
    except Exception:  # noqa: BLE001 — an un-unparseable arg list must not break generation
        return "(...)"


def _parse(path: Path) -> ast.Module | None:
    try:
        return ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError):
        return None


def build_global_index() -> str:
    """Markdown: one row per file (path -> module purpose), grouped by top-level package."""
    by_pkg: dict[str, list[tuple[str, str]]] = {}
    for path in _iter_source_files():
        mod = _parse(path)
        purpose = _first_doc_line(ast.get_docstring(mod)) if mod else "_(unparseable)_"
        by_pkg.setdefault(_package(path), []).append((_rel(path), purpose))

    lines = [
        "# Global code index — apecx_integration",
        "",
        _GENERATED_NOTE,
        "",
        "One row per source file: path -> module purpose (docstring line 1).",
        "",
    ]
    for pkg in sorted(by_pkg):
        lines.append(f"## {pkg}")
        lines.append("")
        lines.append("| File | Purpose |")
        lines.append("|---|---|")
        for rel, purpose in by_pkg[pkg]:
            cell = purpose.replace("|", "\\|") or "—"
            lines.append(f"| `{rel}` | {cell} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_detailed_index() -> str:
    """Markdown: per file, its classes (with bases + methods) and top-level functions."""
    lines = [
        "# Detailed code index — apecx_integration",
        "",
        _GENERATED_NOTE,
        "",
        "Per file: classes (with bases + methods) and top-level functions, each with a compact",
        "signature + docstring line 1. Consult on demand (grep for a symbol), not front-to-back.",
        "",
    ]
    for path in _iter_source_files():
        mod = _parse(path)
        lines.append(f"## `{_rel(path)}`")
        if mod is None:
            # Symmetric with global_index (which marks the file _(unparseable)_) — never
            # silently drop a file, or a grep of the detailed index returns nothing with no reason.
            lines.append("_(unparseable — skipped)_")
            lines.append("")
            continue
        mod_doc = _first_doc_line(ast.get_docstring(mod))
        if mod_doc:
            lines.append(f"_{mod_doc}_")
        lines.append("")
        wrote_member = False
        for node in mod.body:
            if isinstance(node, ast.ClassDef):
                wrote_member = True
                bases = ", ".join(ast.unparse(b) for b in node.bases)
                head = f"- class `{node.name}" + (f"({bases})" if bases else "") + "`"
                doc = _first_doc_line(ast.get_docstring(node))
                lines.append(head + (f" — {doc}" if doc else ""))
                for sub in node.body:
                    if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                        prefix = "async def" if isinstance(sub, ast.AsyncFunctionDef) else "def"
                        mdoc = _first_doc_line(ast.get_docstring(sub))
                        lines.append(
                            f"  - `{prefix} {sub.name}{_signature(sub)}`"
                            + (f" — {mdoc}" if mdoc else "")
                        )
            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                wrote_member = True
                prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
                doc = _first_doc_line(ast.get_docstring(node))
                lines.append(
                    f"- `{prefix} {node.name}{_signature(node)}`" + (f" — {doc}" if doc else "")
                )
        if not wrote_member:
            lines.append("_(no module-level classes or functions)_")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate/verify the apecx_integration code index."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if either index file differs from freshly generated output.",
    )
    args = parser.parse_args()

    targets = {GLOBAL_INDEX: build_global_index(), DETAILED_INDEX: build_detailed_index()}

    if args.check:
        stale = [
            p
            for p, content in targets.items()
            if not p.exists() or p.read_text(encoding="utf-8") != content
        ]
        if stale:
            names = ", ".join(_rel(p) for p in stale)
            print(
                f"code index is STALE: {names}\n  run: .venv/bin/python scripts/gen_index.py",
                file=sys.stderr,
            )
            return 1
        return 0

    GLOBAL_INDEX.parent.mkdir(parents=True, exist_ok=True)
    for path, content in targets.items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {_rel(path)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
